### ISSUE TITLE
Not working with TypeScript

### ISSUE THREAD

**Issue by sulitprod** [baseballyama/svelte-preprocess-delegate-events#24]
I installed the preprocessor, configured everything, and now these errors appear in the console and the application does not work

<img width="658" alt="Снимок экрана 2023-05-19 в 12 34 09" src="https://github.com/baseballyama/svelte-preprocess-delegate-events/assets/70243378/420c3d88-d18c-4a31-b130-8f02de796611">

**Comment by baseballyama** [comment]
Thank you for reporting the issue!
I will fix this ASAP.😅
(Today I'm AFK, so I will try to fix this tomorrow.)
