### ISSUE TITLE
Bug: Using `on:` with `svelte:element` gives an error

### ISSUE THREAD

**Issue by abdel-17** [baseballyama/svelte-preprocess-delegate-events#51]
Due to how variables are named, the preprocessor produces invalid code when it's used with Svelte's special tags like `svelte:element`.

See the screenshot below:

<img width="713" alt="Screenshot 2023-08-22 at 4 30 00 PM" src="https://github.com/baseballyama/svelte-preprocess-delegate-events/assets/88583085/47486d75-d6f1-4778-858c-86f94a9963dd">

**Comment by baseballyama** [comment]
Thank you! I will fix this bug!

**Comment by baseballyama** [comment]
This is fixed in v0.4.2!🎉
